name: Generate and Deploy HTML

on:
  push:
    branches:
      - master  # Run this workflow on pushes to the 'master' branch
  workflow_dispatch:  # Allow manual triggering from GitHub UI

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:

    # Step 1: Check out the repository
    - name: Check out repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    # Step 1: Set up Git credentials for Overleaf
    - name: Configure Git for Overleaf
      env:
        OVERLEAF_USERNAME: git  # Overleaf username/email
        OVERLEAF_PASSWORD: ${{ secrets.OVERLEAF_TOKEN }}  # Overleaf password
      run: |
        git config --global credential.helper store
        echo "https://${OVERLEAF_USERNAME}:${OVERLEAF_PASSWORD}@git.overleaf.com" > ~/.git-credentials

    - name: Clone Overleaf Repository
      run: |
        git clone https://git.overleaf.com/652e2007b1424ca05dac54c4 cv

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    # Step 4: Run Python script to generate HTML
    - name: Generate HTML
      run: |
        python generate_html.py

    - name: Generate PDF
      uses: xu-cheng/latex-action@v3
      with:
          root_file: cv/cv.tex
          texlive_version: 2023

    # Step 5: Deploy to GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .  # Deploy the repository root (with the generated HTML)